# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8
xcode_project: ./Example/Example.xcodeproj # path to your xcodeproj folder
xcode_scheme: Example
xcode_sdk: iphonesimulator10.0
script: xcodebuild -project ./Example/Example.xcodeproj -target Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

#script:
# - set -o pipefail && xcodebuild test -workspace Example/KSimpleSideMenu.xcworkspace -scheme KSimpleSideMenu-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint
